spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher


# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bigeventserver.pojo
  configuration:
    map-underscore-to-camel-case: true

# 配置日志信息
logging:
  level:
    com:
      bigeventserver:
        mapper: debug
        service: info
        controller: info

# JWT
jwt:
  token-name: token
  ttl: 3600000 # 一小时
  secret-key: wwt-big-event
